### PR TITLE
[WIP] update: underline stays active

### PR DESCRIPTION
**Pull request by FroudeDescartes**

### CODE REVIEW

**Review by jpradocueva — APPROVED** [review]
@FroudeDescartes. It is approved. Can we merge it? The PR is marked as WIP

**Comment by jpradocueva** [comment]
@FroudeDescartes, do we also need to make the line on the vertical menus thicker?

**Comment by FroudeDescartes** [comment]
@jpradocueva I can make it thicker, but I probably won`t go with the same amount as for the main menus

**Comment by FroudeDescartes** [comment]
> @FroudeDescartes. It is approved. Can we merge it? The PR is marked as WIP

@jpradocueva  Let`s not merge it yet, I still have to figure out a way for underline in main menus to stay active even if you navigate on the left-hand side menus

**Comment by jpradocueva** [comment]
@FroudeDescartes  Ok, it sounds good.
Do you think that we should also increase the width of the vertical line on the left and right menus?

**Comment by FroudeDescartes** [comment]
> @jpradocueva I can make it thicker, but I probably won`t go with the same amount as for the main menus

Yes

**Review by rubystream — APPROVED** [review]
LGTM

**Comment by jpradocueva** [comment]
@FroudeDescartes, I have checked and am unsure if the vertical lines in the left menu have changed. Did you apply any changes?
What about the right menu? Do you think that it would look good to have the same effect?

**Comment by FroudeDescartes** [comment]
> @FroudeDescartes, I have checked and am unsure if the vertical lines in the left menu have changed. Did you apply any changes? What about the right menu? Do you think that it would look good to have the same effect?

@jpradocueva It should be visible. Here are comparisons

imageimage

**Comment by FroudeDescartes** [comment]
@jpradocueva 
Right aside and main menus are now done. They are showing as we want so I will mere this PR, to avoid conflicts

**Pull request merged**
