### PR TITLE
update: added png images

### PR DESCRIPTION
**Pull request by FroudeDescartes**
In `/oma-events/test-events` images that were in  `.jpeg` are now in `.png` resulting in no background spill. However, in dark mode, old OMA logo does not look nicely.

image

We need old OMA logo with white fonts. Do we have any? @jpradocueva

### CODE REVIEW

**Comment by jpradocueva** [comment]
@FroudeDescartes I cannot find a suitable dark oma log (old logo). Therefore, let's use the OMASpecworks instead.

**Comment by jpradocueva** [comment]
@FroudeDescartes I have changed the old logo for the new logo, but now it doesn't look good in light-mode. Obviously, that dark logo shouldn't be used in this case.
Can you please resolve this issue? Thanks

**Comment by FroudeDescartes** [comment]
@jpradocueva This should now be resolved

**Review by jpradocueva — APPROVED** [review]
@FroudeDescartes problem solved. I am merging it now.

**Pull request merged**
