### PR TITLE
fix: bg now appears full in pages with less content than full height of viewport

### PR DESCRIPTION
**Pull request by FroudeDescartes**
**First image shows the state of background before this PR, and 2nd is after**
> NOTE: on some external displays with low color accuracy these images can appear the same. Best compare on native screen (if better than external ones)  🚨

image

image

### CODE REVIEW

**Comment by jpradocueva** [comment]
@FroudeDescartes, unfortunately, there are still some pages that have that problem. See the LwM2M landing page below.
image

**Comment by jpradocueva** [comment]
@FroudeDescartes actually, I have realized that it happens to all the pages that need to scroll up to view content

**Comment by FroudeDescartes** [comment]
I suppose that this is due to OS or browser. In my browser, everything is looking good. I did made a corelation between pages that need scroll and the ones that does not. Will see what can be done more.

image

**Comment by FroudeDescartes** [comment]
@jpradocueva @gocadimic 
Can you guys provide me with feedback if the background is corrected or is it still rendering with issues?

**Review by jpradocueva — APPROVED** [review]
@FroudeDescartes the problem has been resolved! I am merging it now.

**Pull request merged**
