### PR TITLE
F.A.Q is tidied up by topic

### PR DESCRIPTION
**Pull request by gocadimic**

### CODE REVIEW

**Comment by jpradocueva** [comment]
@gocadimic I am getting some warnings that we need to investigate before merging it.
image

Can you find an alternative image? This is too large and it is not aligned with the rest of the images theme. Also, we will need to find a place for the content at the end of the FAQ as it shouldn't be there. But we can discuss it tomorrow.

**Comment by gocadimic** [comment]
@jpradocueva, please check again. I am not getting any errors. I updated it with some minor changes.

**Comment by gocadimic** [comment]
@jpradocueva, the open section image was replaced.

**Comment by jpradocueva** [comment]
I have resolved some conflicts, and now it seems okay. Can we discuss tomorrow the last content on F.A.Q file? What do you want to do with that content?

**Comment by gocadimic** [comment]
@jpradocueva, There is some content at the end of the page related to TestFest that we can shift to Events/Test Events.
I will propose a resolution to a new issue.

**Review by jpradocueva — APPROVED** [review]
ok to merge

**Pull request merged**
